export const data = [
  {
    id: 1,
    name: "Alice Johnson",
    age: 28,
    email: "alice.johnson@example.com",
  },
  {
    id: 2,
    name: "Bob Smith",
    age: 35,
    email: "bob.smith@example.com",
  },
  {
    id: 3,
    name: "Charlie Brown",
    age: 42,
    email: "charlie.brown@example.com",
  },
  {
    id: 4,
    name: "David Lee",
    age: 31,
    email: "david.lee@example.com",
  },
  {
    id: 5,
    name: "Emma Wilson",
    age: 29,
    email: "emma.wilson@example.com",
  },
  {
    id: 6,
    name: "Frank Davis",
    age: 37,
    email: "frank.davis@example.com",
  },
  {
    id: 7,
    name: "Grace Taylor",
    age: 26,
    email: "grace.taylor@example.com",
  },
  {
    id: 8,
    name: "Henry Clark",
    age: 33,
    email: "henry.clark@example.com",
  },
  {
    id: 9,
    name: "Ivy Martinez",
    age: 40,
    email: "ivy.martinez@example.com",
  },
  {
    id: 10,
    name: "Jack White",
    age: 36,
    email: "jack.white@example.com",
  },
  {
    id: 11,
    name: "Kelly Carter",
    age: 27,
    email: "kelly.carter@example.com",
  },
  {
    id: 12,
    name: "Liam Harris",
    age: 34,
    email: "liam.harris@example.com",
  },
  {
    id: 13,
    name: "Mia Garcia",
    age: 30,
    email: "mia.garcia@example.com",
  },
  {
    id: 14,
    name: "Noah Rodriguez",
    age: 38,
    email: "noah.rodriguez@example.com",
  },
  {
    id: 15,
    name: "Olivia Martinez",
    age: 25,
    email: "olivia.martinez@example.com",
  },
  {
    id: 16,
    name: "Peter Adams",
    age: 32,
    email: "peter.adams@example.com",
  },
  {
    id: 17,
    name: "Quinn Mitchell",
    age: 39,
    email: "quinn.mitchell@example.com",
  },
  {
    id: 18,
    name: "Rachel Walker",
    age: 28,
    email: "rachel.walker@example.com",
  },
  {
    id: 19,
    name: "Samuel Hall",
    age: 35,
    email: "samuel.hall@example.com",
  },
  {
    id: 20,
    name: "Tina Nelson",
    age: 41,
    email: "tina.nelson@example.com",
  },
  {
    id: 21,
    name: "Ursula Thompson",
    age: 26,
    email: "ursula.thompson@example.com",
  },
  {
    id: 22,
    name: "Victor Wright",
    age: 33,
    email: "victor.wright@example.com",
  },
  {
    id: 23,
    name: "Wendy Harris",
    age: 29,
    email: "wendy.harris@example.com",
  },
  {
    id: 24,
    name: "Xavier King",
    age: 36,
    email: "xavier.king@example.com",
  },
  {
    id: 25,
    name: "Yvonne Scott",
    age: 27,
    email: "yvonne.scott@example.com",
  },
  {
    id: 26,
    name: "Zoe Baker",
    age: 34,
    email: "zoe.baker@example.com",
  },
  {
    id: 27,
    name: "Adam Green",
    age: 31,
    email: "adam.green@example.com",
  },
  {
    id: 28,
    name: "Barbara White",
    age: 38,
    email: "barbara.white@example.com",
  },
  {
    id: 29,
    name: "Chris Lopez",
    age: 25,
    email: "chris.lopez@example.com",
  },
  {
    id: 30,
    name: "Diana Taylor",
    age: 32,
    email: "diana.taylor@example.com",
  },
];
